name: Docker Publish

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'smb.conf'
      - '.github/workflows/docker-publish.yml'

  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'entrypoint.sh'
      - 'smb.conf'
      - '.github/workflows/docker-publish.yml'

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:

      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v7.0.1

      # Enable ARM64 builds through QEMU
      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v4.2.0

      # Set up Docker Buildx
      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v4.2.0

      # Login to GitHub Container Registry
      - name: Docker Login
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4.6.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Generate Docker image metadata
      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      # Build and push multi-platform Docker image
      - name: Build and push Docker images
        id: build-and-push
        uses: docker/build-push-action@v7.3.0
        with:
          context: .

          platforms: linux/amd64,linux/arm64

          push: ${{ github.event_name != 'pull_request' }}

          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}

          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Install Cosign
      - name: cosign-installer
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v4.1.2

      # Sign the published Docker image
      - name: Sign the published Docker image
        if: github.event_name != 'pull_request'
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        run: |
          echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}
